"""
Unified DTOs (Data Transfer Objects) for application layer.
This module centralizes all Pydantic response models used by the API.
For backward compatibility, these are re-exported from the existing schemas module.
"""

from app.schemas import (
    # Basic responses
    PriceResponse,
    OptionQuoteOut,
    OptionsChainResponse,
    GreeksAtStrike,
    GreeksResponse,
    StrikeExposureOut,
    ExposureResponse,
    MaxPainResponse,
    HeatmapCell,
    HeatmapResponse,
    ExpirationsResponse,
    # Analysis responses
    GammaAnalysisResponse,
    DeltaAnalysisResponse,
    OptionsAnalysisResponse,
    VolatilityAnalysisResponse,
    DealerAnalysisResponse,
    IntelligenceScoresResponse,
    ConfidenceDetailsResponse,
    RegimeDetailsResponse,
    ScenarioResponse,
    ScenarioCollectionResponse,
    IntelligenceResponse,
    # Query responses
    QueryResponse,
    QuestionItem,
    QuestionsListResponse,
    HedgingStrengthResponse,
    YieldAnomalyResponse,
    AnomalyItemOut,
    # Evidence engine responses
    EvidenceTypeEnum,
    SourceReliabilityEnum,
    EvidenceItemOut,
    EvidenceSummaryOut,
    EvidenceCollectionOut,
    ConflictDetectionOut,
    EvidenceGapOut,
    EvidenceReportOut,
    # Prediction tracking responses
    PredictionTypeEnum,
    PredictionOutcomeEnum,
    PredictionCreateIn,
    PredictionOut,
    PredictionEvaluateIn,
    AccuracyMetricsOut,
    ConfidenceAdjustmentOut,
    CalibrationReportOut,
    PredictionMetricsOut,
)

__all__ = [
    # Basic responses
    "PriceResponse",
    "OptionQuoteOut",
    "OptionsChainResponse",
    "GreeksAtStrike",
    "GreeksResponse",
    "StrikeExposureOut",
    "ExposureResponse",
    "MaxPainResponse",
    "HeatmapCell",
    "HeatmapResponse",
    "ExpirationsResponse",
    # Analysis responses
    "GammaAnalysisResponse",
    "DeltaAnalysisResponse",
    "OptionsAnalysisResponse",
    "VolatilityAnalysisResponse",
    "DealerAnalysisResponse",
    "IntelligenceScoresResponse",
    "ConfidenceDetailsResponse",
    "RegimeDetailsResponse",
    "ScenarioResponse",
    "ScenarioCollectionResponse",
    "IntelligenceResponse",
    # Query responses
    "QueryResponse",
    "QuestionItem",
    "QuestionsListResponse",
    "HedgingStrengthResponse",
    "YieldAnomalyResponse",
    "AnomalyItemOut",
    # Evidence engine responses
    "EvidenceTypeEnum",
    "SourceReliabilityEnum",
    "EvidenceItemOut",
    "EvidenceSummaryOut",
    "EvidenceCollectionOut",
    "ConflictDetectionOut",
    "EvidenceGapOut",
    "EvidenceReportOut",
    # Prediction tracking responses
    "PredictionTypeEnum",
    "PredictionOutcomeEnum",
    "PredictionCreateIn",
    "PredictionOut",
    "PredictionEvaluateIn",
    "AccuracyMetricsOut",
    "ConfidenceAdjustmentOut",
    "CalibrationReportOut",
    "PredictionMetricsOut",
]
